### ISSUE TITLE
Python example grammars are broken

### ISSUE THREAD

**Issue by chris-hexx** [erezsh/lark#48]
parser=Lark(open("python2.g.txt").read())

fails with 

Traceback (most recent call last):
  File "D:/Users/502744471/Desktop/Projects/GEPyPlot/code/GMC_parser.py", line 53, in <module>
    parser=Lark(open("python2.g.txt").read())
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\lark.py", line 151, in __init__
    self.grammar = load_grammar(grammar, source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\load_grammar.py", line 612, in load_grammar
    resolve_token_references(token_defs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\load_grammar.py", line 513, in resolve_token_references
    raise GrammarError("Rules aren't allowed inside tokens (%s in %s)" % (item, name))
lark.common.GrammarError: Rules aren't allowed inside tokens (s in LONG_STRING)

And parser=Lark(open("python3.g.txt").read())

results in 

Traceback (most recent call last):
  File "D:/Users/502744471/Desktop/Projects/GEPyPlot/code/GMC_parser.py", line 53, in <module>
    parser=Lark(open("python3.g.txt").read())
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\lark.py", line 159, in __init__
    self.parser = self._build_parser()
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\lark.py", line 180, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\parser_frontends.py", line 122, in __init__
    rules = [(n, list(self._prepare_expansion(x)), a, o) for n,x,a,o in parser_conf.rules]
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\parser_frontends.py", line 122, in <listcomp>
    rules = [(n, list(self._prepare_expansion(x)), a, o) for n,x,a,o in parser_conf.rules]
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark\parser_frontends.py", line 137, in _prepare_expansion
    width = sre_parse.parse(regexp).getwidth()
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 768, in _parse
    source.tell() - start)
sre_constants.error: missing ), unterminated subpattern at position 12

[python2.g.txt](https://github.com/erezsh/lark/files/1549397/python2.g.txt)
[python3.g.txt](https://github.com/erezsh/lark/files/1549398/python3.g.txt)

In python3.g.txt I've tried to simplify the test case down by changing the definition of LONG_STRING.

Any ideas? Looking at it casually I think that the regex parser doesn't believe that the STRING token regex is complete and is trying to parse the LONG_STRING token regex as another part of it.

**Comment by erezsh** [comment]
Which version of Lark are you using?
Can you try it with the latest `master` commit? (currently 53a56d5)

**Comment by FRidh** [comment]
Could make `parser=Lark(open("python3.g.txt").read())` a test.

**Comment by chris-hexx** [comment]
Updating to 53a56d5 changed the problem I'm seeing, but did resolve the original complaint. Is the convention to mark this issue resolved and open another with the new bug?

If no: parsing fails on the attached parsertest.py with the grammar from /examples/python3.g
[parsertest.py.txt](https://github.com/erezsh/lark/files/1552233/parsertest.py.txt)

**Comment by erezsh** [comment]
I'm not a stickler to procedures, so it's fine that we continue here.
However, when you report an error, I do ask that you provide the exception you're getting.

**Comment by chris-hexx** [comment]
Oops, of course. I modified the test case slightly to get the traceback, yielding
Traceback (most recent call last):
  File "D:/Users/502744471/Desktop/Projects/GEPyPlot/code/parsertest.py", line 18, in <module>
    tree = parser.parse(text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark_parser-0.4.1-py3.6.egg\lark\lark.py", line 189, in parse
    return self.parser.parse(text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark_parser-0.4.1-py3.6.egg\lark\parser_frontends.py", line 143, in parse
    return self.parser.parse(text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark_parser-0.4.1-py3.6.egg\lark\parsers\xearley.py", line 130, in parse
    column = scan(i, token, column)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lark_parser-0.4.1-py3.6.egg\lark\parsers\xearley.py", line 119, in scan
    raise UnexpectedInput(stream, i, text_line, text_column, to_scan)
lark.lexer.UnexpectedInput: No token defined for: 'l' in 'log.d' at line 7 col 5

for the attached parsertest.py
[parsertest.py.txt](https://github.com/erezsh/lark/files/1556115/parsertest.py.txt)

**Comment by erezsh** [comment]
Okay, so a quick question: Why are you using Earley to parse it? The `Python3.g` that comes with Lark is specifically designed for use with LALR(1), which is a lot faster.

**Comment by chris-hexx** [comment]
No great reason. I'm trying to reverse-engineer a language definition that parses existing files, so whatever works first is what sticks, until perf matters. Using Earley is a holdover from that environment.

**Comment by erezsh** [comment]
Wait, so it this the exact python grammar provided with the examples, or did you make any changes to it?

**Comment by chris-hexx** [comment]
Just to be sure, I re-decompressed from the GitHub download: yes, I'm using the grammar from 53a56d5:/examples/python3.g unmodified.

**Comment by erezsh** [comment]
Well, I suggest you go back to `examples/python_parser.py` and see how I initialize the parser:

    python_parser3 = Lark(f, parser='lalr', postlex=PythonIndenter(), start='file_input')     

The python grammar requires a postlex adaptor to handle indentation. If you don't care about performance, and you want to make changes to the grammar, it makes sense to use Earley for it. Then what you have to do is this:

    python_parser3 = Lark(f, lexer='standard', postlex=PythonIndenter(), start='file_input')     

Good luck!

**Comment by chris-hexx** [comment]
It didn't even occur to me to look at /examples/python_parser.py . Using the postlexer works beautifully. Thanks for the correction and your time building the library.
