### ISSUE TITLE
Packaging 0.5.0 test failed : AttributeError: 'module' object has no attribute 'test_parser'

### ISSUE THREAD

**Issue by tigerfoot** [erezsh/lark#54]
During the refresh of package for openSUSE I got errors during the %check pass

```
[   22s] + mv _build.python2 build
[   22s] + echo python2
[   22s] + /usr/bin/python2 setup.py test
[   22s] running test
[   22s] running egg_info
[   22s] writing lark_parser.egg-info/PKG-INFO
[   22s] writing top-level names to lark_parser.egg-info/top_level.txt
[   22s] writing dependency_links to lark_parser.egg-info/dependency_links.txt
[   22s] package init file 'lark/grammars/__init__.py' not found (or not a regular file)
[   22s] reading manifest file 'lark_parser.egg-info/SOURCES.txt'
[   22s] reading manifest template 'MANIFEST.in'
[   22s] writing manifest file 'lark_parser.egg-info/SOURCES.txt'
[   22s] running build_ext
[   22s] Traceback (most recent call last):
[   22s]   File "setup.py", line 53, in <module>
[   22s]     "License :: OSI Approved :: MIT License",
[   22s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
[   22s]     return distutils.core.setup(**attrs)
[   22s]   File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
[   22s]     dist.run_commands()
[   22s]   File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
[   22s]     self.run_command(cmd)
[   22s]   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
[   22s]     cmd_obj.run()
[   22s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 226, in run
[   22s]     self.run_tests()
[   22s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 248, in run_tests
[   22s]     exit=False,
[   22s]   File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
[   22s]     self.parseArgs(argv)
[   22s]   File "/usr/lib64/python2.7/unittest/main.py", line 113, in parseArgs
[   22s]     self._do_discovery(argv[2:])
[   22s]   File "/usr/lib64/python2.7/unittest/main.py", line 214, in _do_discovery
[   22s]     self.test = loader.discover(start_dir, pattern, top_level_dir)
[   22s]   File "/usr/lib64/python2.7/unittest/loader.py", line 206, in discover
[   22s]     tests = list(self._find_tests(start_dir, pattern))
[   22s]   File "/usr/lib64/python2.7/unittest/loader.py", line 287, in _find_tests
[   22s]     for test in self._find_tests(full_path, pattern):
[   22s]   File "/usr/lib64/python2.7/unittest/loader.py", line 268, in _find_tests
[   22s]     yield self.loadTestsFromModule(module)
[   22s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
[   22s]     tests.append(self.loadTestsFromName(submodule))
[   22s]   File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
[   22s]     parent, obj = obj, getattr(obj, part)
[   22s] AttributeError: 'module' object has no attribute 'test_parser'
[   22s] error: Bad exit status from /var/tmp/rpm-tmp.knFpkP (%check)
```
Full build log is available [here](https://build.opensuse.org/build/home:bruno_friedmann:branches:devel:languages:python/openSUSE_Tumbleweed/x86_64/python-lark-parser/_log)
Is there anything I've missed ?

**Comment by erezsh** [comment]
No, it's my bad. Never tried to run the tests this way. It should work now. Uploaded lark 0.5.1

**Comment by tigerfoot** [comment]
Yeap super cool, it's working so I'm closing it

**Comment by erezsh** [comment]
Excellent.
So you're adding lark as a package in OpenSUSE?  Just curious what prompted you to do so :)

**Comment by tigerfoot** [comment]
Yeap super cool, it's working so I'm closing it
