### ISSUE TITLE
Error message from parser says rule already exists even though the rule is only defined once

### ISSUE THREAD

**Issue by iamburitto** [erezsh/lark#60]
Hi,

I'm having trouble with the metadata rule in the following script:

```python
from lark import Lark

schema_parser = Lark('''
    schema: include* (type_decl | enum_decl | root_decl | object )*
    include: "include" STRING_CONSTANT ";"
    type_decl: ( "table" | "struct" ) IDENT metadata "{" field_decl+ "}"
    enum_decl: ( "enum" IDENT [ ":" type ] | "union" IDENT ) metadata "{" [ enumval_decl ( "," enumval_decl )* ] "}"
    root_decl: "root_type" IDENT ";"
    field_decl: IDENT ":" type [ "=" scalar ] metadata ";"
    type: "bool" | "byte" | "ubyte" | "short" | "ushort" | "int" | "uint" | "float" | "long" | "ulong" | "double" | "int8" | "uint8" | "int16" | "uint16" | "int32" | "uint32" | "int64" | "uint64" | "float32" | "float64" | "string" | [ type ] | IDENT
    enumval_decl: IDENT [ "=" integer_constant ]
    metadata : [ ( [ IDENT [ ":" single_value ] ( "," IDENT [ ":" single_value ] )* ] ) ]
    scalar: integer_constant | FLOAT_CONSTANT
    object: "{" [  IDENT ":" value  ( ","  IDENT ":" value  )* ] "}"
    single_value: scalar | STRING_CONSTANT
    value: single_value | object | [  value  ( ","  value  )* ]
    file_extension_decl: "file_extension" STRING_CONSTANT ";"
    integer_constant: /-?[0-9]+/ | "true" | "false"
    FLOAT_CONSTANT: /-?[0-9]+.[0-9]+((e|E)(+|-)?[0-9]+)?/
    STRING_CONSTANT: /\".*?\\"/
    IDENT: /[a-zA-Z_][a-zA-Z0-9_]*/
    
    // %import common.WS
    // %ignore WS
    // %ignore " "

    ''', start='schema')
```
When running the above, I get the following output:
```bash
"C:\Program Files\Python36\python.exe" C:/Users/britt.christy/Documents/repos/git/altair/kashmir_software/submodules/code_generator/FlatBuffers/parser/lark/altair_schema_lark.py
Traceback (most recent call last):
  File "C:/Users/britt.christy/Documents/repos/git/altair/kashmir_software/submodules/code_generator/FlatBuffers/parser/lark/altair_schema_lark.py", line 27, in <module>
    ''', start='schema')
  File "C:\Program Files\Python36\lib\site-packages\lark\lark.py", line 155, in __init__
    self.parser = self._build_parser()
  File "C:\Program Files\Python36\lib\site-packages\lark\lark.py", line 170, in _build_parser
    callback = self._parse_tree_builder.create_callback(self.options.transformer)
  File "C:\Program Files\Python36\lib\site-packages\lark\parse_tree_builder.py", line 156, in create_callback
    raise GrammarError("Rule '%s' already exists" % (rule,))
lark.common.GrammarError: Rule '<metadata : >' already exists
```
Can you help me understand what is wrong with my metadata rule that makes the parser think it is defined more than once?

Thanks!

**Comment by erezsh** [comment]
Hi,

The reason you get an exception is that metadata defines the empty rule twice. It should work if you rewrote it as:

    metadata : [ IDENT [ ":" single_value ] ( "," IDENT [ ":" single_value ] )* ]

However, this exception is a usability bug, so I pushed a fix to master. Your old grammar should work just fine if you use the most recent commit  (5fd331b).

P.S. You'll probably want to mark `type` as `!type` to keep the values inside it (or turn them into a terminal).

**Comment by iamburitto** [comment]
Thanks for the quick reply and advice about "type"!

I tried out your updated metadata definition, and I don't get the same error as before, so I believe this issue is closed.

I installed lark using pip - I assume you won't be updating that package until you have a new release, so I'll go ahead and clone your source to test it out with my original metadata definition. 

Thanks again!

**Comment by erezsh** [comment]
No problem, happy to help :)
