### ISSUE TITLE
Difficulty tracing "nothing to repeat error" to a problem with the grammar input

### ISSUE THREAD

**Issue by iamburitto** [erezsh/lark#62]
This is my current grammar definition when building a Lark object:

```python
from lark import Lark

schema_parser = Lark('''
    // RULES
    
    schema : include* (type_decl | enum_decl | root_decl | object )*
    include : "include" STRING_CONSTANT ";"
    type_decl : ( "table" | "struct" ) IDENT "{" field_decl+ "}"
    enum_decl : ( "enum" IDENT [ ":" TYPE ] | "union" IDENT ) "{" [ enumval_decl ( "," enumval_decl )* ] "}"
    root_decl : "root_type" IDENT ";"
    field_decl : IDENT ":" TYPE [ "=" SCALAR ] ";"
    enumval_decl: IDENT [ "=" INTEGER_CONSTANT ]
    object : "{" [  IDENT ":" value  ( ","  IDENT ":" value  )* ] "}"
    value : SCALAR | STRING_CONSTANT | object | [  value  ( ","  value  )* ]
    
    // TERMINALS
    
    SCALAR : INTEGER_CONSTANT | FLOAT_CONSTANT | BOOLEAN_CONSTANT
    BOOLEAN_CONSTANT : "true" | "false" 
    INTEGER_CONSTANT : /-?[0-9]+/ | BOOLEAN_CONSTANT
    FLOAT_CONSTANT : /-?[0-9]+.[0-9]+((e|E)(+|-)?[0-9]+)?/
    STRING_CONSTANT : /\".*?\\"/
    IDENT : /[a-zA-Z_][a-zA-Z0-9_]*/
    TYPE : "bool" | "byte" | "ubyte" | "short" | "ushort" | "int" | "uint" | "float" | "long" | "ulong" | "double" | "int8" | "uint8" | "int16" | "uint16" | "int32" | "uint32" | "int64" | "uint64" | "float32" | "float64" | "string" | IDENT
    
    // Imports and ignores
    %import common.WS
    %ignore WS
```

When running the script, I get the following error output:

```bash
"C:\Program Files\Python36\python.exe" C:/Users/britt.christy/Documents/repos/git/altair/kashmir_software/submodules/code_generator/FlatBuffers/parser/lark/altair_schema_lark.py
Traceback (most recent call last):
  File "C:/Users/britt.christy/Documents/repos/git/altair/kashmir_software/submodules/code_generator/FlatBuffers/parser/lark/altair_schema_lark.py", line 30, in <module>
    ''', start='schema')
  File "C:\Program Files\Python36\lib\site-packages\lark\lark.py", line 155, in __init__
    self.parser = self._build_parser()
  File "C:\Program Files\Python36\lib\site-packages\lark\lark.py", line 178, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "C:\Program Files\Python36\lib\site-packages\lark\parser_frontends.py", line 108, in __init__
    self._prepare_match(lexer_conf)
  File "C:\Program Files\Python36\lib\site-packages\lark\parser_frontends.py", line 124, in _prepare_match
    assert sre_parse.parse(regexp).getwidth()
  File "C:\Program Files\Python36\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files\Python36\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files\Python36\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files\Python36\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files\Python36\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files\Python36\lib\sre_parse.py", line 616, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 56
```

I'm not finding this error specific enough to figure out what is wrong with my grammar, clarification appreciated! Might be a good idea to tweak the error messages to be a little more specific about which part of the grammar triggered the error.

**Comment by erezsh** [comment]
Hi Britt,
You have an error in your regexp at FLOAT_CONSTANT
It's
    FLOAT_CONSTANT : /-?[0-9]+.[0-9]+((e|E)(+|-)?[0-9]+)?/
But it should be
    FLOAT_CONSTANT : /-?[0-9]+.[0-9]+((e|E)(\+|-)?[0-9]+)?/
(notice the escaping on the plus)

Generally, I suggest to avoid regexps when possible, and instead use Lark's builtin operators. For example, common.g (https://github.com/erezsh/lark/blob/master/lark/grammars/common.g) implements a FLOAT terminal without a regular expression.

**Comment by erezsh** [comment]
I do agree that a better error message is warranted however, so thanks for helping me debug the user interface!

**Comment by iamburitto** [comment]
Switched to using Lark's built in float, works great. Thanks!
