### ISSUE TITLE
'Tree' object has no attribute 'flags'

### ISSUE THREAD

**Issue by eddieschoute** [erezsh/lark#97]
When parsing my grammar file Lark throws an exception that the Tree object does not have the attribute flags.

## Expected Behavior
Lark should either throw an error that the grammar file is incorrect or parse the grammar file and produce a parser.

## Current Behavior
Lark throws an exception when parsing the grammar and it is unclear what is wrong. I do not immediately see how my grammar is wrong (it probably is since I'm new to Lark), but it seems like an internal error of Lark's.

When parsing my grammar
[quipper.g.txt](https://github.com/erezsh/lark/files/1767694/quipper.g.txt)
I get the following exception:
```
>>> from lark import Lark
>>> with open('quipper.g') as grammar_file:
...     Lark(grammar_file.read())
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/lark.py", line 156, in __init__
    tokens, self.rules, self.ignore_tokens = self.grammar.compile(lexer=bool(lexer), start=self.options.start)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/load_grammar.py", line 485, in compile
    for name, (token_tree, priority) in token_defs]
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/load_grammar.py", line 485, in <listcomp>
    for name, (token_tree, priority) in token_defs]
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/tree.py", line 139, in transform
    tree = t.transform(tree)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/tree.py", line 113, in transform
    items.append(self.transform(c) if isinstance(c, Tree) else c)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/tree.py", line 121, in transform
    return f(items)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/load_grammar.py", line 387, in expansions
    if len({i.flags for i in exps}) > 1:
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/load_grammar.py", line 387, in <setcomp>
    if len({i.flags for i in exps}) > 1:
AttributeError: 'Tree' object has no attribute 'flags'
```

As you can see, the grammar is still incomplete, but I was working on debugging it.

## Environment
OS: MacOS 10.13
Lark version: 0.5.4

**Comment by erezsh** [comment]
Yes, at a first glance it seems that the error occurs because you are using aliases in terminals, which isn't allowed. You could solve this by turning the terminals to rules. For example:

    SUB_CONTROL : "yes" -> yes

into

    sub_control : "yes" -> yes

Having said that, you're absolutely right that I should put a better error message in place, as it's a very reasonable mistake to make.

**Comment by eddieschoute** [comment]
Great, that seems to have resolved the exception. Thanks! I'll leave the issue open so that you can implement better error reporting for this kind of error.

**Comment by erezsh** [comment]
Fixed.

**Comment by gueugang** [comment]
It looks like you are trying to use the Lark parser, but there may be some confusion with the attribute names. It's possible that the parser_default_config attribute doesn't exist in the version of Lark you are using. It's recommended to check the documentation or the source code for the version of Lark you are using to ensure that you are using the correct attribute names.

If you need further assistance, feel free to provide more details about what you are trying to achieve, and I'd be happy to help! 🤖
svp besoin d'aide
