### ISSUE TITLE
LALR parser throws gives UnexpectedToken exception with optional string

### ISSUE THREAD

**Issue by eddieschoute** [erezsh/lark#98]
I have written a grammar that succesfully passes my testcases with the default parser. Now I am trying to convert it to an LALR parser. But this parser throws an exception when parsing a fairly sentence.

## Expected Behavior
Lark should either give an error that certain constructions in the grammar are not allowed for LALR parsing or parse the grammar correctly.

## Current Behavior
I have the following grammar rule:
```
qgate       : "QGate[" STRING "]" ["*"] "(" INT ")"
```
which I apply to the following sentence
```
QGate["not"](0)
```
This worked succesfully in with the normal parser, but with the LALR parser I get an error
```
Error
Traceback (most recent call last):
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 46, in get_action
    return states[state][key]
KeyError: '__ANONSTR_8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/eddie/dev/quippy/test_quipper_parser.py", line 44, in test_gatelist_qgate
    parsed = parser.parse(basic_text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/lark.py", line 197, in parse
    return self.parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parser_frontends.py", line 37, in parse
    return self.parser.parse(token_stream)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 73, in parse
    action, arg = get_action(token.type)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 50, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(__ANONSTR_8, '](') at line 1, column 11.
Expected: dict_keys(['__RSQB'])
Context: <no context>
```

When I modify the text to (by adding a '*')
```
QGate["not"]*(0)
```
it parses succesfully. Alternatively, I can change the grammar rule to
```
qgate       : "QGate[" STRING "](" INT ")"
```
and that also works. It would seem to me that an optional symbol should be possible in an LR grammar (please correct me if I'm wrong), so where does this go awry?

## Environment
OS: MacOS 10.13
Lark: 0.5.4

**Comment by erezsh** [comment]
Okay, so here's the reason for the error. In LALR, the lexer is by design deterministic. So if it has two terminals somewhere in the grammar, `]` and `](`, and it sees `](` in the input, it has to choose between them, and cannot try both. By default it chooses the longer one, though you can change that with priority.

What I'm saying is, somewhere else in the grammar there's a `](` terminal, and I suggest you break it into `]` and `(`.

**Comment by eddieschoute** [comment]
Yes, thank you. It is clear I needed to learn how a lexer behaves.
