### ISSUE TITLE
Lexers ignore literal priority

### ISSUE THREAD

**Issue by eddieschoute** [erezsh/lark#99]
Given two literals to choose from, the lexers parse terminals to the one with lower priority.

## Expected Behavior
The higher priority terminal should be parsed first, resulting in the terminal being `FOO` instead of `BAR`.

## Current Behavior
The terminal `BAR` is produced causing the test case to fail.
Test case
```
def test_testlex(self):
    grammar = '''
    %import common.WS -> WS
    %ignore WS

    start: FOO
    
    FOO.2: "Test" ":" "foo"
    BAR: "Test"
    '''
    text = """Test: foo"""
    parser = Lark(grammar, parser='lalr')
    parsed = parser.parse(text)
```
This gives an error
```
Error
Traceback (most recent call last):
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 46, in get_action
    return states[state][key]
KeyError: 'BAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/eddie/dev/quippy/test_quipper_parser.py", line 176, in test_testlex
    parsed = parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/lark.py", line 197, in parse
    return self.parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parser_frontends.py", line 37, in parse
    return self.parser.parse(token_stream)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 73, in parse
    action, arg = get_action(token.type)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 50, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(BAR, 'Test') at line 1, column 0.
Expected: dict_keys(['FOO', 'start'])
Context: <no context>
```

For the normal earley parser we have the same issue but the error message is less descriptive:
```
def test_testlex(self):
    grammar = '''
    %import common.WS -> WS
    %ignore WS
    
    start : FOO
    
    FOO.2: "Test" ":" "foo"
    BAR: "Test"
    '''
    text = """Test: foo"""
    parser = Lark(grammar)
    parsed = parser.parse(text)
```
with errror
```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/eddie/dev/quippy/test_quipper_parser.py", line 176, in test_testlex
    parsed = parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/lark.py", line 197, in parse
    return self.parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parser_frontends.py", line 137, in parse
    return self.parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/xearley.py", line 126, in parse
    column = scan(i, column)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/xearley.py", line 115, in scan
    raise UnexpectedInput(stream, i, text_line, text_column, {item.expect for item in to_scan})
lark.lexer.UnexpectedInput: No token defined for: 'T' in 'Test:' at line 1 col 0

Expecting: {'FOO'}
```

I am mostly going off the behavior described in the [wiki](https://github.com/erezsh/lark/wiki/Grammar-Reference), where it claims that it will try to lex to literals of the highest priority first. Removing the priority also does not help (even though the `FOO` literal is longer than `BAR` literal so it should be parsed first).

Oddly enough, removing the `%ignore WS` (and manually removing the whitespace in the test text) resolves the issue. So maybe whitespace is not being ignored in time by the lexer?

**Comment by eddieschoute** [comment]
It seems that whitespace is being lexer after `FOO` is lexed causing the test cause to fail because it contains whitespace. To resolve this I could manually add whitespace to the `FOO` rule so that it does parse.
I presume this is done to allow literals of the form `foo bar` to be parsed into one literal, before whitespace lexing comes in and removes the space.

Is there a nicer way to construct terminals of the form
```
TERM: FOO WS BAR WS ":" WS ...
```
without manually inserting whitespace between every literal? Or would you suggest making `TERM` a normal rule instead?

**Comment by eddieschoute** [comment]
The cause of this issue is the following.
I'm trying to parse the grammar
```
start : circuit subroutine*

circuit : "Inputs:" arity (gate NEWLINE)* "Outputs:" arity

subroutine: NEWLINE "Subroutine" ":" STRING NEWLINE "Shape:" STRING NEWLINE "Controllable:" SUB_CONTROL NEWLINE circuit
...
```
which works for a file that begins with
```
Inputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit, 10:Qbit, 11:Qbit, 12:Qbit, 13:Qbit, 14:Qbit, 15:Qbit, 16:Qbit, 17:Qbit, 18:Qbit, 19:Qbit, 20:Qbit, 21:Qbit, 22:Qbit, 23:Qbit, 24:Qbit, 25:Qbit, 26:Qbit, 27:Qbit, 28:Qbit, 29:Qbit
Subroutine(x1)["L", shape "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"] (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29) -> (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29)
Subroutine(x11157790)["C", shape "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"] (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29) -> (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29)
Subroutine(x1)["R", shape "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"] (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29) -> (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29)
Outputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit, 10:Qbit, 11:Qbit, 12:Qbit, 13:Qbit, 14:Qbit, 15:Qbit, 16:Qbit, 17:Qbit, 18:Qbit, 19:Qbit, 20:Qbit, 21:Qbit, 22:Qbit, 23:Qbit, 24:Qbit, 25:Qbit, 26:Qbit, 27:Qbit, 28:Qbit, 29:Qbit
 
Subroutine: "L"
Shape: "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"
Controllable: yes
Inputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit, 10:Qbit, 11:Qbit, 12:Qbit, 13:Qbit, 14:Qbit, 15:Qbit, 16:Qbit, 17:Qbit, 18:Qbit, 19:Qbit, 20:Qbit, 21:Qbit, 22:Qbit, 23:Qbit, 24:Qbit, 25:Qbit, 26:Qbit, 27:Qbit, 28:Qbit, 29:Qbit
QGate["H"](0) with nocontrol
...
```
but does not for a file
```
Inputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit, 10:Qbit, 11:Qbit, 12:Qbit, 13:Qbit, 14:Qbit, 15:Qbit, 16:Qbit, 17:Qbit, 18:Qbit, 19:Qbit, 20:Qbit, 21:Qbit, 22:Qbit, 23:Qbit, 24:Qbit, 25:Qbit, 26:Qbit, 27:Qbit, 28:Qbit, 29:Qbit
Subroutine(x3591360)["S6", shape "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"] (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29) -> (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29)
Outputs: 0:Qbit, 1:Qbit, 2:Qbit, 3:Qbit, 4:Qbit, 5:Qbit, 6:Qbit, 7:Qbit, 8:Qbit, 9:Qbit, 10:Qbit, 11:Qbit, 12:Qbit, 13:Qbit, 14:Qbit, 15:Qbit, 16:Qbit, 17:Qbit, 18:Qbit, 19:Qbit, 20:Qbit, 21:Qbit, 22:Qbit, 23:Qbit, 24:Qbit, 25:Qbit, 26:Qbit, 27:Qbit, 28:Qbit, 29:Qbit

Subroutine: "S6"
Shape: "([Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q,Q],())"
Controllable: yes
...
```
where it fails with the error
```
Error
Traceback (most recent call last):
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 46, in get_action
    return states[state][key]
KeyError: '__SUBROUTINE2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eddie/dev/quippy/test_quipper_parser.py", line 190, in test_optimizer
    parser.parse(quipper_file.read())
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/lark.py", line 197, in parse
    return self.parser.parse(text)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parser_frontends.py", line 37, in parse
    return self.parser.parse(token_stream)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 73, in parse
    action, arg = get_action(token.type)
  File "/Users/eddie/dev/quippy/.venv/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 50, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(__SUBROUTINE2, 'Subroutine') at line 5, column 0.
Expected: dict_keys(['NEWLINE', '$END'])
Context: <no context>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/eddie/dev/quippy/test_quipper_parser.py", line 192, in test_optimizer
    raise RuntimeError(f"Failed to parse {path}. Error: {e}")
RuntimeError: Failed to parse resources/optimizer/PF/pf6_30_before. Error: Unexpected token Token(__SUBROUTINE2, 'Subroutine') at line 5, column 0.
Expected: dict_keys(['NEWLINE', '$END'])
Context: <no context>
```
so I tried turning the subroutine into a literal header follow by the circuit, which would (by the above reasoning) necessitate inserting whitespace manually.
If I replace the contents of the second file entirely with the contents of the first, the same error occurs. But the first file is parsed succesfully and the second is not. This would almost indicate to me there is some kind of nondeterminism going on (although it very deterministically always fails for the second file).

For completeness' sake, the full grammar is [quipper.g.txt](https://github.com/erezsh/lark/files/1771983/quipper.g.txt) . I am using the LALR parser. The earley parser is very slow on the second file (that has 38k lines).

**Comment by eddieschoute** [comment]
Ah, one issue was that `common.NEWLINE` actually matches multiple newlines, so removing that seems to have helped, given that I was expecting a newline leading into a subroutine call.

**Comment by erezsh** [comment]
Also, note that terminals are "atomic", so `%ignore WS` doesn't apply to spaces inside them.
